apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.8-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            name: mysql-pass
            key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/www/html
    volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: wp-pvc
