apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysqlv2
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 2000
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: wpuser
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wpbd
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: "mysql-pvc-v2"
