apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mysql-pvc"
  namespace: "tp2-1844129-2192070"
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accesModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: mysql-pv
