apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mysql-pvc-v2"
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: mysql-pv-v2
