apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mysql-pv-v2"
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.100.2.90
    path: "/srv/exports/tp2-1844129-2192070-v2"