apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: tp2-1844129-2192070-v2
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 31033
      targetPort: 3306
  type: NodePort
  
