apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysqlv2
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30033
      targetPort: 3306
  type: NodePort
  
