apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysqlv2
  labels:
    app: wordpress
    tier: mysql
spec:
  selector:
    app: wordpress
    tier: mysql
  ports:
    - port: 3306
      nodePort: 30033
      targetPort: 3306
  type: NodePort
  
